@startuml
'https://plantuml.com/class-diagram

class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    - {static} instance:HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + {static} getInstance():HeroAircraft
    + forward():void
    + shoot():List<AbstractBullet>
}

Client -> HeroAircraft::getInstance
HeroAircraft::instance --> HeroAircraft

@enduml