@startuml
'https://plantuml.com/class-diagram

Interface UserDao{
    {abstract} getAllUserList():List<User>
    {abstract} deleteRecord(User user):void
    {abstract} printUserRanking():void
    {abstract} addUser(User user):void
}

Class UserDaoList implements UserDao{
    + getAllUserList():List<User>
    + deleteRecord(User user):void
    + printUserRanking():void
    + addUser(User user):void
}

class User implements Serializable{
    - name:String
    - score:int
    - gameDate:Date
    + User(String name, int score, Date gameDate)
    + toString():String
    + getScore():int
    + setScore(int score):void
    + getName():String
    + setName(String name):void
    + compareTo(User o):int
}

class Game{
}

Game ..>UserDao
UserDaoList -right-> User

@enduml